### ISSUE TITLE
Index Error in get_total_rows

### ISSUE THREAD

**Issue by Coelodonta** [mariostoev/finviz#167]
I'm using finviz 1.4.6 with Python 3.10 and Ubuntu 22.04. If I run the sample code from the github README file I get the error below. The same code worked well until last week, when I started getting this error. Suggestions?

The code is simply:

from finviz.screener import Screener

filters = ['exch_nasd', 'idx_sp500'] 
stock_list = Screener(filters=filters, table='Performance', order='price') 

The error is:

Traceback (most recent call last):
  File "/home/fq01/finviz_test.py", line 4, in <module>
    stock_list = Screener(filters=filters, table='Performance', order='price')
  File "/home/fq01/venv/lib/python3.10/site-packages/finviz/screener.py", line 128, in __init__
    self.data = self.__search_screener()
  File "/home/fq01/venv/lib/python3.10/site-packages/finviz/screener.py", line 436, in __search_screener
    self._rows = self.__check_rows()
  File "/home/fq01/venv/lib/python3.10/site-packages/finviz/screener.py", line 404, in __check_rows
    self._total_rows = scrape.get_total_rows(self._page_content)
  File "/home/fq01/venv/lib/python3.10/site-packages/finviz/helper_functions/scraper_functions.py", line 46, in get_total_rows
    etree.tostring(total_element[0]).decode("utf-8").split("</b>")[1].split()[0]
IndexError: list index out of range

**Comment by PBbanana** [comment]
I can confirm this error. 

IDK if it matters, but I get the error even after applying the fix to whitespace characters #168

**Comment by PBbanana** [comment]
Here is a temporary workaround that worked for me: 

change the get_total_rows function to:

def get_total_rows(page_content):
    """ Returns the total number of rows(results). """

    total_element = page_content.cssselect('td[width="128"]')
    total_number = (total_element[0].text.split()[2])

    try:
        return int(total_number)
    except ValueError:
        return 0

**Comment by Coelodonta** [comment]
PBbanana,
Unfortunately, that fix didn't work for me. Still getting errors. Thanks anyway!

**Comment by vpereira** [comment]
@PBbanana and @Coelodonta using the version from git, it works. However it needs the patch from #168 then I'm able to get the table as expected

**Comment by AGG2017** [comment]
I don't see 'td[width="128"]' in the html content anymore and get_total_rows() fails.
My workaround at the moment is this one:
```
def get_total_rows(page_content):
    """ Returns the total number of rows(results). """
    import lxml.html
    total_number = str(lxml.html.tostring(page_content)).split('class="count-text">#1 / ')[1].split(' Total</td>')[0]
    try:
        return int(total_number)
    except ValueError:
        return 0
```

**Comment by AGG2017** [comment]
It is more complex now, from time to time it changes to 'class="count-text whitespace-nowrap">#1 / '
I did it like this:
```
def get_total_rows(page_content):
    """ Returns the total number of rows(results). """

    options=['class="count-text whitespace-nowrap">#1 / ','class="count-text">#1 / ']
    page_text = str(html.tostring(page_content))
    print(page_text)
    for option in options:
        if option in page_text:
            total_number = page_text.split(option)[1].split(' Total</td>')[0]
            try:
                return int(total_number)
            except ValueError:
                return 0
    return 0
```

but when filtering for S&P500 I see also more troubles when extracting the rows. It needs more work.

**Comment by thor-cognitica** [comment]
Thanks! This fix seems to work. (At least for now LOL!)

**Comment by mariostoev** [comment]
Fixed in v2.0.0. Please upgrade: `pip install --upgrade finviz`
