### ISSUE TITLE
SyntaxError: invalid syntax around finviz/screener.py  line 113

### ISSUE THREAD

**Issue by klepsydra** [mariostoev/finviz#30]
What might be causing this error?

``` 
Traceback (most recent call last):
  File "./robin_stocks.API.py", line 163, in <module>
    result = rhLib.apiRun(args.method, args.parameters)
  File "/home/master/www/robinbot/rhLib.py", line 232, in apiRun
    result= eval(method + parameters)  # <class 'dict'>
  File "<string>", line 1, in <module>
  File "/home/master/www/robinbot/rhLib.py", line 457, in fullQuote
    import finviz
  File "/usr/local/lib/python3.5/dist-packages/finviz/__init__.py", line 1, in <module>
    from finviz.screener import Screener
  File "/usr/local/lib/python3.5/dist-packages/finviz/screener.py", line 113
    values = f'tickers: {tuple(self._tickers)}\n' \
                                                ^
SyntaxError: invalid syntax

```

My Python script merely uses `finvizData = finviz.get_stock(symbol)` , but the Syntax Error happens right at `import finviz` wherever it's placed.

I did 
`pip install finviz`
under all versions installed locally or globally (Python 2.7.12 built-in to Ubuntu 16.04.6 LTS, Python 3.5 and Python 3.6).

**Comment by andrewjylee** [comment]
I've been able to reproduce this error in Python3.5 but not with Python3.6?

**Comment by andrewjylee** [comment]
[PEP 498](https://www.python.org/dev/peps/pep-0498/) introduces `f-strings` in Python3.6 - I would expect the SyntaxError for Python2.7 and Python3.5. Are you sure you've encountered this issue with Python3.6 as well?

**Comment by klepsydra** [comment]
Closing since works under Python 3.6.8
