### ISSUE TITLE
No module named 'user_agent' bug

### ISSUE THREAD

**Issue by inquisb** [mariostoev/finviz#48]
Bug report:

```
# python3 example.py
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    from finviz.helper_functions.save_data import export_to_db, export_to_csv
  File "/mnt/c/Users/consultant/Documents/software/finviz/finviz/__init__.py", line 1, in <module>
    from finviz.screener import Screener
  File "/mnt/c/Users/consultant/Documents/software/finviz/finviz/screener.py", line 1, in <module>
    from finviz.helper_functions.request_functions import Connector, http_request_get
  File "/mnt/c/Users/consultant/Documents/software/finviz/finviz/helper_functions/request_functions.py", line 3, in <module>
    from user_agent import generate_user_agent
ModuleNotFoundError: No module named 'user_agent'
```

**Comment by baophamtd** [comment]
@inquisb maybe you can try `pip install user_agent`?
