### ISSUE TITLE
TypeError: download_chart_image() missing 1 required positional argument: 'url'

### ISSUE THREAD

**Issue by ghost355** [mariostoev/finviz#76]
This error appear when I try to get charts with get_charts(). I just upgrade to actual version, Before I had no such error

**Comment by d3an** [comment]
@ghost355 I'm getting a fix together for this issue among a few others. Should be ready soon.

**Comment by ghost355** [comment]
I am still getting error
`>>> b.get_charts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/.pip-modules/lib/python3.8/site-packages/finviz/screener.py", line 336, in get_charts
    async_connector.run_connector()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/finviz/helper_functions/request_functions.py", line 101, in run_connector
    loop.run_until_complete(self.__async_scraper())
  File "/home/gitpod/.pyenv/versions/3.8.6/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/finviz/helper_functions/request_functions.py", line 95, in __async_scraper
    self.data = await asyncio.gather(*async_tasks)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/finviz/helper_functions/request_functions.py", line 77, in __http_request__async
    return self.scrape_function(page_html, *self.arguments)
TypeError: download_chart_image() missing 1 required positional argument: 'url'`

**Comment by sienedo** [comment]
i'm still having problem with this. even after updating to latest one

**Comment by calmoon808** [comment]
I am also having this issue
