### ISSUE TITLE
API down?

### ISSUE THREAD

**Issue by bollingerbandit** [mariostoev/finviz#88]
Hi, 

I've been playing around with this project and wanted to say thank you first and foremost. 

I was wondering if anything has broken recently? Here is what my error looks like when i try to run the example 

```
python3 example.py
^C

Traceback (most recent call last):
  File "/Users/archan.brahmbhatt/Scripts/me/finviz/example.py", line 12, in <module>
    stock_list = Screener(filters=some_filters, order='ticker')
  File "/Users/archan.brahmbhatt/Scripts/me/finviz/finviz/screener.py", line 115, in __init__
    self.data = self.__search_screener()
  File "/Users/archan.brahmbhatt/Scripts/me/finviz/finviz/screener.py", line 386, in __search_screener
    self._page_content, self._url = http_request_get('https://finviz.com/screener.ashx', payload={
  File "/Users/archan.brahmbhatt/Scripts/me/finviz/finviz/helper_functions/request_functions.py", line 30, in http_request_get
    content = requests.get(url, params=payload, verify=False, headers={'User-Agent': generate_user_agent()})
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
KeyboardInterrupt
```

Am i doing something wrong ? Worked a okay last week.

**Comment by d3an** [comment]
Works fine for me (MacOS for both Python 3.8 & 3.9). Should be using this:
```bash
$ pip install -U git+https://github.com/mariostoev/finviz
```
