### ISSUE TITLE
Screener and example.py not working

### ISSUE THREAD

**Issue by pascaloberle** [mariostoev/finviz#99]
Hi there! 
Thanks for the great tool that I am looking forward to use :)
I try to run the basic code from the screener with Python `3.8.5 as below:

```
from finviz.screener import Screener

filters = ['exch_nasd', 'idx_sp500']  # Shows companies in NASDAQ which are in the S&P500
stock_list = Screener(filters=filters, table='Performance', order='price')  # Get the performance table and sort it by price ascending

# Export the screener results to .csv
stock_list.to_csv("stock.csv")
```

And below is the error I would get 
![image](https://user-images.githubusercontent.com/6572717/116699597-1a716a00-aa09-11eb-861f-2793ed650402.png)

**TypeError: expected string or bytes-like object** when parsing HTML data from FinViz

**Comment by pascaloberle** [comment]
Running the python example file as well

` python example.py    
  0%|                                                     | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    stock_list = Screener(filters=some_filters, order="ticker")
  File "/Users/poberle/Downloads/finviz-master 2/finviz/screener.py", line 128, in __init__
    self.data = self.__search_screener()
  File "/Users/poberle/Downloads/finviz-master 2/finviz/screener.py", line 455, in __search_screener
    self._rows,
  File "/Users/poberle/Downloads/finviz-master 2/finviz/helper_functions/request_functions.py", line 71, in sequential_data_scrape
    raise exc
  File "/Users/poberle/Downloads/finviz-master 2/finviz/helper_functions/request_functions.py", line 69, in sequential_data_scrape
    data.append(scrape_func(response, *args, **kwargs))
  File "/Users/poberle/Downloads/finviz-master 2/finviz/helper_functions/scraper_functions.py", line 11, in get_table
    page_parsed = html.fromstring(page_html)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/lxml/html/__init__.py", line 874, in fromstring
    is_full_html = _looks_like_full_html_unicode(html)
TypeError: expected string or bytes-like object`

**Comment by gopar** [comment]
Getting same error

**Comment by jiajunxiong** [comment]
Hi, please review my Pull request, will solve the issue.
